name: CI Test
on:
  push:
    paths:
      - 'src/**'

jobs:
  ci_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: 'adopt'
      - name: Gradle Test
        run: ./gradlew build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rankup
          path: build/libs/*.jar
